# This file is the entry point to configure your own services.
# Files in the packages/ subdirectory configure your dependencies.

# Put parameters here that don't need to change on each machine where the app is deployed
# https://symfony.com/doc/current/best_practices.html#use-parameters-for-application-configuration
parameters:
#    env(MAILER_DSN): 'smtp://%env(resolve:MAILER_USER)%:%env(resolve:MAILER_PASSWORD)%@%env(MAILER_SERVER)%:%env(MAILER_PORT)%'
    app.website_url: '%env(WEBSITE)%'
    app.frontend_url: '%env(FRONTEND_URL)%'
    app.contact_email: '%env(EMAIL)%'
    app.phone_number: '%env(PHONE)%'
    github_token: '%env(GITHUB_TOKEN)%'
    github_repo_owner: '%env(GITHUB_REPO_OWNER)%'
    github_repo_name: '%env(GITHUB_REPO_NAME)%'
    vapid_public_key: '%env(VAPID_PUBLIC_KEY)%'
    vapid_private_key: '%env(VAPID_PRIVATE_KEY)%'
    weather_api_url: '%env(WEATHER_API_URL)%'

services:
    # default configuration for services in *this* file
    _defaults:
        autowire: true      # Automatically injects dependencies in your services.
        autoconfigure: true # Automatically registers your services as commands, event subscribers, etc.
        bind:
            $vapidPublicKey: '%env(resolve:VAPID_PUBLIC_KEY)%'
            $vapidPrivateKey: '%env(resolve:VAPID_PRIVATE_KEY)%'
            $githubToken: '%env(resolve:GITHUB_TOKEN)%'
            $githubRepoOwner: '%env(resolve:GITHUB_REPO_OWNER)%'
            $githubRepoName: '%env(resolve:GITHUB_REPO_NAME)%'
            $weatherApiUrl: '%env(resolve:WEATHER_API_URL)%'
            $frontendUrl: '%env(resolve:FRONTEND_URL)%'
            $mailerFrom: '%env(resolve:MAILER_FROM)%'

    # Monolog channel bindings for custom loggers
    Psr\Log\LoggerInterface $xpProcessingLogger: '@monolog.logger.xp_processing'
    Psr\Log\LoggerInterface $cronLogger: '@monolog.logger.cron'

    # makes classes in src/ available to be used as services
    # this creates a service per class whose id is the fully-qualified class name
    App\:
        resource: '../src/'
        exclude:
            - '../src/DependencyInjection/'
            - '../src/Kernel.php'
    
    # Configure DataFixtures as services with autowiring
    App\DataFixtures\:
        resource: '../src/DataFixtures/'
        tags: ['doctrine.fixture.orm']

    App\Security\JWTUserChecker:
        tags:
            - { name: 'monolog.logger', channel: 'security' }

    Symfony\Component\Serializer\Normalizer\ObjectNormalizer:
        arguments:
            $classMetadataFactory: '@serializer.mapping.class_metadata_factory'
            $defaultContext:
                enable_max_depth: true

    serializer.mapping.class_metadata_factory:
        class: Symfony\Component\Serializer\Mapping\Factory\ClassMetadataFactory
        arguments: ['@serializer.mapping.loader.attribute_loader']

    serializer.mapping.loader.attribute_loader:
        class: Symfony\Component\Serializer\Mapping\Loader\AttributeLoader

    Symfony\Component\Serializer\Normalizer\DateTimeNormalizer:
        arguments:
            $defaultContext:
                datetime_format: 'Y-m-d'

    App\Adapter\GoogleDriveAdapter:
        arguments:
            $clientId: '%env(GOOGLE_CLIENT_ID)%'
            $clientSecret: '%env(GOOGLE_CLIENT_SECRET)%'
            $refreshToken: '%env(GOOGLE_REFRESH_TOKEN)%'
            $folderId: '%env(GOOGLE_FOLDER_ID)%'

#    App\EventListener\JWTExpiredListener:
#        tags:
#            - { name: kernel.event_listener, event: lexik_jwt_authentication.on_jwt_invalid, method: onJWTInvalid }

    # add more service definitions when explicit configuration is needed
    # please note that last definitions always *replace* previous ones
